apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-kv-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-kv-reader
  template:
    metadata:
      labels:
        app: vault-kv-reader
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: VAULT_ADDR
              value: "{{ .Values.vault.addr }}"
            
            - name: VAULT_VERIFY_TLS
              value: {{ .Values.vault.verifyTLS | quote }}

            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-token
                  key: token

            # Dev-safe TLS handling
            - name: VAULT_SKIP_VERIFY
              value: "true"